services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=secret
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nextcloud -d nextcloud -h 127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  nc:
    image: nextcloud:apache
    restart: always
    ports:
      - "8081:80"               #listinin port 
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=secret
      - POSTGRES_HOST=db
    volumes:
      - nc_data:/var/www/html

volumes:
  db_data:
  nc_data:

